export const currencyNameToCode: Map<string, string> = new Map([
	['Euro', 'EUR'],
	['US-Dollar', 'USD'],
	['Britisches Pfund', 'GBP'],
	['Schweizer Franken', 'CHF'],
	['Kanadischer Dollar', 'CAD'],
	['Australischer Dollar', 'AUD'],
	['Neuseeland-Dollar', 'NZD'],
	['Japanischer Yen', 'JPY'],
	['Chinesischer Renminbi', 'CNY'],
	['Hongkong-Dollar', 'HKD'],
	['Singapur-Dollar', 'SGD'],
	['Neuer Taiwan-Dollar', 'TWD'],
	['Thailändischer Baht', 'THB'],
	['Philippinischer Peso', 'PHP'],
	['Malaysischer Ringgit', 'MYR'],
	['Indische Rupie', 'INR'],
	['Mexikanischer Peso', 'MXN'],
	['Brasilianischer Real', 'BRL'],
	['Schwedische Krone', 'SEK'],
	['Norwegische Krone', 'NOK'],
	['Dänische Krone', 'DKK'],
	['Polnischer Złoty', 'PLN'],
	['Ungarischer Forint', 'HUF'],
	['Tschechische Krone', 'CZK'],
	['Israelischer Schekel', 'ILS']
]);

export const currencyCodeToSymbol: Map<string, string> = new Map([
	['EUR', '€'],
	['USD', '$'],
	['GBP', '£'],
	['CHF', 'CHF'],
	['CAD', 'CA$'],
	['AUD', 'A$'],
	['NZD', 'NZ$'],
	['JPY', '¥'],
	['CNY', '¥'],
	['HKD', 'HK$'],
	['SGD', 'S$'],
	['TWD', 'NT$'],
	['THB', '฿'],
	['PHP', '₱'],
	['MYR', 'RM'],
	['INR', '₹'],
	['MXN', '$'],
	['BRL', 'R$'],
	['SEK', 'kr'],
	['NOK', 'kr'],
	['DKK', 'kr'],
	['PLN', 'zł'],
	['HUF', 'Ft'],
	['CZK', 'Kč'],
	['ILS', '₪']
]);
